export { default as Signup } from "./SignUp/Signup";
export { default as Login } from "./Login/Login";
export { default as PrivateComponent } from "./PrivateComponent";
export { default as Home } from "./Home/Home";
export { default as UploadPost } from "./UploadPost/UploadPost";
export { default as Profile } from "./Profile/Profile";
export { default as UpdateProfile } from "./UpdateProfile/UpdateProfile";
export { default as Password } from "./Password/Password";
export { default as Polaris } from "./Polaris/Polaris";
